name: Render Quarto PDF

on:
  push:
    paths:
      - '**.qmd'

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: stable

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install matplotlib

      - name: Render PDF
        run: quarto render scatter.qmd --to pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v4   # 👈 updated from v3 → v4
        with:
          name: scatter-pdf
          path: scatter.pdf
